version: "3.9"

services:
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - ./lumen:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - lumen
      - mysql
    networks:
      - lumen_network
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lumen
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - lumen_network
  lumen:
    build:
      context: .
      dockerfile: ./lumen/Dockerfile
    working_dir: /var/www
    ports:
      - "9000:9000"
    volumes:
      - ./lumen:/var/www
    networks:
      - lumen_network
    stdin_open: true
    tty: true

networks:
  lumen_network:

volumes:
  mysql_volume:
